# stage-1 for build war
FROM maven:3.8.4-openjdk-11-slim AS build-stage
WORKDIR /app
COPY ./pom.xml ./pom.xml
COPY ./src ./src
RUN mvn dependency:go-offline

RUN mvn package

# stage-2 for deploy app into docker
FROM tomcat:8.5.78-jdk11-openjdk-slim

COPY --from=build-stage /app/target/*.war /usr/local/tomcat/webapps/

EXPOSE 8080

CMD ["catalina.sh", "run"]



